name: Bottle

on:
  push:
    tags:
      - '*'

jobs:
  bottle:
    runs-on: macos-13

    steps:
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build bottle
        run: |
          brew install --build-bottle daxchain-io/homebrew-tap/cli-wallet
          brew bottle daxchain-io/homebrew-tap/cli-wallet

      - name: Upload bottle
        uses: actions/upload-artifact@v2
        with:
          name: cli-wallet-bottle
          path: "*.bottle.*"
