name: Update Homebrew Tap

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout homebrew-tap
        uses: actions/checkout@v2
        with:
          repository: daxchain-io/homebrew-tap
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Update URL and hash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          URL="https://github.com/daxchain-io/cli-wallet/archive/refs/tags/$TAG.tar.gz"
          SHA256=$(curl -L $URL | shasum -a 256 | cut -d ' ' -f 1)

          sed -i "s|url .*|url \"$URL\"|" cli-wallet.rb
          sed -i "s|sha256 .*|sha256 \"$SHA256\"|" cli-wallet.rb

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add cli-wallet.rb
          git commit -m "Update cli-wallet to $TAG"
          git push

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: New version ${{ github.ref }}
          draft: false
          prerelease: false
